recruitsql/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from forms_builder.forms import urls as forms_urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from interviews.views import InterviewSessionDetailView, InterviewBookingWizard, INTERVIEW_BOOKING_FORMS, InterviewAppointmentBookingDeleteView
from jobs.views import PositionDetailView, JobApplicationDetailView, JobApplicationListView, PositionJobApplicationListView, JobApplicationDeleteView
from users.views import UserProfileUpdateView, UserUpdateView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'recruitsql.views.home', name='home'),
    # url(r'^recruitsql/', include('recruitsql.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forms/', include(forms_urls)),
    #url(r'^$', PositionListView.as_view(), name="index"),
    url(r'^position/(?P<pk>\d+)$', PositionDetailView.as_view(), name='position_detail'),
    url(r'^apply/(?P<pk>\d+)$', 'jobs.views.application_form_view', name="job_apply"),

    url(r'^$', 'jobs.views.position_filter', name="index"),

    url(r'^accounts/profile$', login_required(UserProfileUpdateView.as_view()), name='update_profile'),
    (r'^accounts/', include('registration_withemail.urls')),
    (r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/check_profile$', 'users.views.check_profile_view', name="check_profile"),
    url(r'^accounts/cv/(?P<uid>\d+)$', 'users.views.get_cv_file', name='get_cv'),
    url(r'^accounts/applications$', login_required(JobApplicationListView.as_view()), name="jobapplication_list"),
    url(r'^accounts/user$', login_required(UserUpdateView.as_view()), name="user_update"),

    url(r'^jobapplication/(?P<pk>\d+)/$', login_required(JobApplicationDetailView.as_view()), name="jobapplication_detail"),
    url(r'position/(\d+)/jobapplications$', login_required(PositionJobApplicationListView.as_view()), name="position_jobapplication_list"),
    url(r'^jobapplication/(?P<pk>\d+)/edit$', 'jobs.views.application_form_view', name='jobapplication_edit', kwargs={'mode': 'edit'}),
    url(r'^jobapplication/(?P<pk>\d+)/delete', login_required(JobApplicationDeleteView.as_view()), name='jobapplication_delete'),

    url(r'^interviews/session/(?P<pk>\d+)/$', InterviewSessionDetailView.as_view(), name="interviewsession_detail"),
    url(r'^interviews/booking$', InterviewBookingWizard.as_view(INTERVIEW_BOOKING_FORMS), name="interview_booking_wizard"),
    url(r'^interviews/booking_start/(?P<request_id>\d+)$', 'interviews.views.booking_start', name="interview_booking_start"),
    url(r'^interviews/booking/(?P<pk>\d+)/cancel$', InterviewAppointmentBookingDeleteView.as_view(), name="interview_appointment_cancel"),
    url(r'^accounts/interviews$', 'interviews.views.user_interviews_view', name="interview_request_list"),

    (r'^manage/', include('jobs_admin.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interviews/models.py
from datetime import timedelta
from django.conf import settings
from django.db import models

# Create your models here.
import math
from django.utils import timezone
from django.utils.formats import date_format

class InterviewRequest(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    job_application = models.ForeignKey('jobs.JobApplication')
    interview_sessions = models.ManyToManyField('InterviewSession')
    booking = models.ForeignKey('InterviewAppointmentBooking', blank=True, null=True, on_delete=models.SET_NULL)
    deadline = models.DateTimeField(blank=True, null=True)

    def is_expired(self):
        if self.deadline:
            return self.deadline < timezone.now()
        return False

    def is_valid(self):
        return not bool(self.booking) and not self.is_expired()

    def get_status(self):
        if self.booking:
            return 'Complete'
        elif self.deadline and self.deadline < timezone.now():
            return 'Expired'
        else:
            return 'Open'



class InterviewSession(models.Model):
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)

    location = models.CharField(blank=True, max_length=255)
    extra_instructions = models.TextField(blank=True, null=True)

    def __unicode__(self):
        if self.start_date.date() == self.end_date.date():
            date_str = "%s, %s - %s" % (
                date_format(self.start_date.date(), 'DATE_FORMAT', use_l10n=True),
                date_format(self.start_date.time(), 'TIME_FORMAT', use_l10n=True),
                date_format(self.end_date.time(), 'TIME_FORMAT', use_l10n=True),
            )
        else:
            date_str = "%s - %s" % (self.start_date, self.end_date,)

        if self.location:
            return "%s (%s)" % (date_str, self.location)
        else:
            return date_str

    def generate_appointments(self, appt_length, break_length=0):
        session_delta = self.end_date - self.start_date
        avail_delta = session_delta + timedelta(minutes=break_length)
        each_seconds = appt_length*60 + break_length*60
        each_delta = timedelta(seconds=each_seconds)
        num_appts = math.floor(avail_delta.total_seconds()/each_seconds)
        next_start = self.start_date
        for i in range(0, int(num_appts), 1):
            InterviewAppointment.objects.create(
                session=self,
                start_time=next_start,
                end_time=next_start+timedelta(seconds=appt_length*60),
            )
            next_start += each_delta

class InterviewAppointmentBookingManager(models.Manager):
    def available(self, **kwargs):
        return self.filter(interviewappointmentbooking=None, **kwargs)


class InterviewAppointment(models.Model):
    session = models.ForeignKey('InterviewSession')
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)

    objects = InterviewAppointmentBookingManager()

    def __unicode__(self):
        return date_format(self.start_time, 'DATETIME_FORMAT', use_l10n=True)

    def is_booked(self):
        return self.interviewappointmentbooking_set.count() > 0

class InterviewAppointmentBooking(models.Model):
    appointment = models.ForeignKey('InterviewAppointment')
    application = models.ForeignKey('jobs.JobApplication')
    booked_at = models.DateTimeField(auto_now_add=True)
    booked_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    notes = models.TextField(blank=True)

interviews/forms.py
from django import forms
from interviews.models import InterviewAppointmentBooking, InterviewAppointment, InterviewSession


class InterviewAppointmentBookingForm(forms.ModelForm):
    class Meta:
        model = InterviewAppointmentBooking
        exclude = ('booked_at', 'appointment', 'application', 'booked_by',)

    def save(self, commit=True):
        instance = super(InterviewAppointmentBookingForm,self).save(commit=False)
        if commit:
            instance.save()
        return instance


class InterviewSessionSelectForm(forms.Form):
    def __init__(self, **kwargs):
        allowed_sessions = kwargs.pop('allowed_sessions', None)
        super(InterviewSessionSelectForm,self).__init__(**kwargs)
        if allowed_sessions:
            self.fields['session'].queryset = allowed_sessions

    session = forms.ModelChoiceField(queryset=InterviewSession.objects.all())

class AppointmentSelectForm(forms.Form):
    def __init__(self, **kwargs):
        session = kwargs.pop('session', None)
        super(AppointmentSelectForm,self).__init__(**kwargs)
        if session:
            self.fields['appointment'].queryset = InterviewAppointment.objects.available(session=session)

    appointment = forms.ModelChoiceField(queryset=InterviewAppointment.objects.available())

interviews/views.py
# Create your views here.
from django.contrib.formtools.wizard.views import SessionWizardView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import DetailView, DeleteView
from interviews.forms import AppointmentSelectForm, InterviewAppointmentBookingForm, InterviewSessionSelectForm
from interviews.models import InterviewAppointmentBooking, InterviewSession, InterviewRequest

INTERVIEW_BOOKING_FORMS = [
    ('session_select', InterviewSessionSelectForm),
    ('appointment_select', AppointmentSelectForm),
    ('appointment_booking', InterviewAppointmentBookingForm),
]

def booking_start(request, request_id):
    ir = get_object_or_404(InterviewRequest, id=request_id)
    request.session['interview_request'] = ir
    return redirect('interview_booking_wizard')

class InterviewBookingWizard(SessionWizardView):

    def get_template_names(self):
        return ["interviews/booking_wizard/%s.html" % self.steps.current, 'interviews/booking_wizard.html']

    def done(self, form_list, **kwargs):
        data = self.get_all_cleaned_data()
        ir = self.storage.data.pop('interview_request')
        booking = InterviewAppointmentBooking(
            appointment = data['appointment'],
            booked_by = self.request.user,
            application = ir.job_application,
        )
        booking.save()
        ir.booking = booking
        ir.save()
        context = RequestContext(self.request)
        context['booking'] = booking

        return render_to_response('interviews/booking_wizard_done.html', context)

    def get_form_kwargs(self, step=None):
        kwargs = {}
        if step == 'session_select':
            ir = self.request.session.get('interview_request',None)
            if ir:
                self.storage.data['interview_request'] = ir
                kwargs.update({'allowed_sessions': ir.interview_sessions.all()})
        elif step == 'appointment_select':
            session = self.get_cleaned_data_for_step('session_select')['session']
            kwargs.update({'session': session})
        return kwargs

    def get(self, request, *args, **kwargs):
        if not self.request.session.get('interview_request'):
            return redirect('interview_request_list')
        if not self.request.session['interview_request'].is_valid():
            context = RequestContext(request)
            return render_to_response('500.html', context)
        return super(InterviewBookingWizard,self).get(request, *args, **kwargs)



    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(InterviewBookingWizard, self).dispatch(request, *args, **kwargs)

class InterviewSessionDetailView(DetailView):
    model = InterviewSession

def user_interviews_view(request):
    context = RequestContext(request)

    context.update({
        'interview_requests': InterviewRequest.objects.filter(job_application__in=request.user.jobapplication_set.all()),
        'interview_bookings': InterviewAppointmentBooking.objects.filter(application__in=request.user.jobapplication_set.all()) #, appointment__start_time__gt=timezone.now())
    })

    return render_to_response('interviews/interviewrequest_list.html', context)

class InterviewAppointmentBookingDeleteView(DeleteView):
    model = InterviewAppointmentBooking

    def get_queryset(self):
        return InterviewAppointmentBooking.objects.filter(application__in=self.request.user.jobapplication_set.all())

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, "Your appointment has been cancelled. You may now be able to rebook using the link below.")
        return reverse_lazy('interview_request_list')

templates/interviews/booking_wizard.html
{% extends 'account_home.html' %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block account_main %}

    <div class="large-12 columns">

        <h2>Interview booking</h2>

        <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>

        {% block intro_text %}{% endblock %}
        <form action="" method="post">
            {% csrf_token %}
            {{ wizard.management_form }}
            {% if wizard.form.forms %}
                {% for form in wizard.form.forms %}
                    {{ form.as_p }}
                {% endfor %}
            {% else %}
                {{ wizard.form.as_p }}
            {% endif %}

            {% if wizard.steps.prev %}
                <button name="wizard_goto_step" type="submit" class="secondary"
                        value="{{ wizard.steps.first }}">{% trans "Start again" %}</button>
                <button name="wizard_goto_step" type="submit" class="secondary"
                        value="{{ wizard.steps.prev }}">{% trans "Back" %}</button>
            {% endif %}
            {% if wizard.steps.next %}
            <button type="submit" value="submit">Next</button>
            {% else %}
            <button type="submit" value="submit">Finish</button>
            {% endif %}

        </form>


    </div>


{% endblock %}

templates/interviews/booking_wizard_done.html
{% extends 'account_home.html' %}

{% block account_main %}
    <h2>Booking confirmation</h2>

    <p>Thanks, your interview booking is now confirmed as follows:</p>

    <table>
    <tbody>
    <tr>
        <th>Time:</th>
        <td>{{ booking.appointment.start_time }}</td>
    </tr>
    <tr>
        <th>Location:</th>
        <td>{{ booking.appointment.session.location }}</td>
    </tr>
    </tbody>
    </table>

    <p>{{ booking.appointment.session.extra_instructions }}</p>


    <a class="button secondary" href="{% url 'interview_request_list' %}">Continue</a>

{% endblock %}

templates/interviews/interviewappointmentbooking_confirm_delete.html
{% extends 'account_home.html' %}

{% block account_main %}

<h2>Confirm</h2>

<p>Are you sure you want to cancel the following interview?</p>

<table>
    <tr>
        <th>Date/time</th>
        <td>{{ object.appointment.start_time }}</td>
    </tr>
    <tr>
        <th>Location</th>
        <td>{{ object.appointment.session.location }}</td>
    </tr>
</table>

<form action="" method="post">
    {% csrf_token %}
    <button class="alert" type="submit">Cancel interview</button>
    <a class="button secondary" href="{% url 'interview_request_list' %}">Go back</a>
</form>

{% endblock %}

templates/interviews/interviewappointmentbooking_form.html
{% extends 'base.html' %}

{% block main %}

<div class="large-12 columns">
    <h2>Book interview</h2>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

templates/interviews/interviewrequest_list.html
{% extends 'account_home.html' %}

{% block account_main %}

<div class="large-12 columns">
    <h2>Interviews</h2>

    {% include '_messages.html' %}

    {% if interview_requests %}

    <h3>Interview requests</h3>

    <table>
        <thead>
        <tr>
            <th>Your ref.</th>
            <th>Organisation</th>
            <th>Position</th>
            <th>Status</th>
            <th>Deadline</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for ir in interview_requests %}
        <tr>
            <td>{{ ir.job_application.application_code }}</td>
            <td>{{ ir.job_application.organisation }}</td>
            <td>{{ ir.job_application.position }}</td>
            <td>{{ ir.get_status }}</td>
            <td>{{ ir.deadline }}</td>
            <td>
                {% if ir.is_valid %}
                <a href="{% url 'interview_booking_start' ir.id %}" class="button small secondary">Book</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
        <h3>Interview bookings</h3>

    {% endif %}


    {% if interview_bookings %}


    <table>
        <thead>
        <tr>
            <th>Date/time</th>
            <th>Location</th>
            <th>Your ref</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for booking in interview_bookings %}
        <tr>
            <td>{{ booking.appointment.start_time }}</td>
            <td>{{ booking.appointment.session.location }}</td>
            <td>
                <a href="{% url 'jobapplication_detail' booking.application.id %}">#{{ booking.application.application_code }}</a>
            </td>
            <td><a href="{% url 'interview_appointment_cancel' booking.id %}" class="button alert small">Cancel</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You have no interview bookings at the moment.</p>
    {% endif %}
</div>

{% endblock %}

templates/interviews/interviewsession_detail.html
{% extends 'base.html' %}

{% block main %}

    <div class="large-12 columns">
    <h1>Interview session</h1>

    <table>
        {% for slot in object.interviewappointment_set.all %}
        <tr>
            <th>{{ slot.start_time.time }}</th>
            <td>
                {% if not slot.is_booked %}
                    <a class="button small secondary" href="{% url 'interviews_booking_create' object.id slot.id %}">Book</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    </div>


{% endblock %}